<a href="https://colab.research.google.com/github/MelisaRS/PruebaColab/blob/DataPreparation/CosineSimilarity_Embebing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.2/255.2 kB 3.0 MB/s eta 0:00:00


In [ ]:
from sentence_transformers import SentenceTransformer, util

# Cargar modelo preentrenado multilingüe (funciona para muchos idiomas, incluido el quechua)
model = SentenceTransformer('distiluse-base-multilingual-cased-v1')

# Lista de oraciones en español y quechua
spanish_sentences = [
    "El gato está en la casa.",
    "Estoy estudiando.",
    "El sol brilla en el cielo."
]

quechua_sentences = [
    "Misi wasipi kachkan.",  # El gato está en la casa.
    "Yachaykuyta ruwanqani.",  # Estoy estudiando.
    "Inti hanaqpachapi k'anchan."  # El sol brilla en el cielo.
]

# Generar embeddings para las oraciones en español y quechua
spanish_embeddings = model.encode(spanish_sentences, convert_to_tensor=True)
quechua_embeddings = model.encode(quechua_sentences, convert_to_tensor=True)

# Calcular la similitud de coseno entre cada oración en español y quechua
cosine_scores = util.pytorch_cos_sim(spanish_embeddings, quechua_embeddings)

# Mostrar las puntuaciones de similitud (matriz de similitud)
print("Matriz de Cosine Similarity:")
print(cosine_scores)


/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/341 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.47k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/556 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/452 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

2_Dense/config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.58M [00:00<?, ?B/s]

Matriz de Cosine Similarity:
tensor([[0.1315, 0.0706, 0.1247],
        [0.1771, 0.1661, 0.1741],
        [0.1218, 0.1474, 0.0744]])


In [ ]:
from sentence_transformers import SentenceTransformer, util

# Cargar modelo preentrenado multilingüe (funciona para muchos idiomas, incluido el quechua)
model = SentenceTransformer('xlm-r-bert-base-nli-stsb-mean-tokens')

# Lista de oraciones en español y quechua
spanish_sentences = [
    "El gato está en la casa.",
    "Estoy estudiando.",
    "El sol brilla en el cielo."
]

quechua_sentences = [
    "Misi wasipi kachkan.",  # El gato está en la casa.
    "Yachaykuyta ruwanqani.",  # Estoy estudiando.
    "Inti hanaqpachapi k'anchan."  # El sol brilla en el cielo.
]

# Generar embeddings para las oraciones en español y quechua
spanish_embeddings = model.encode(spanish_sentences, convert_to_tensor=True)
quechua_embeddings = model.encode(quechua_sentences, convert_to_tensor=True)

# Calcular la similitud de coseno entre cada oración en español y quechua
cosine_scores = util.pytorch_cos_sim(spanish_embeddings, quechua_embeddings)

# Mostrar las puntuaciones de similitud (matriz de similitud)
print("Matriz de Cosine Similarity:")
print(cosine_scores)


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.05k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/722 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/518 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Matriz de Cosine Similarity:
tensor([[0.0349, 0.2326, 0.1210],
        [0.0869, 0.1339, 0.1133],
        [0.1510, 0.1631, 0.2122]])


In [ ]:
from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer
import torch
from sentence_transformers import SentenceTransformer, util

# Cargar el modelo M2M-100 y el tokenizer
model_name = "facebook/m2m100_418M"
tokenizer = M2M100Tokenizer.from_pretrained(model_name)
model = M2M100ForConditionalGeneration.from_pretrained(model_name)

# Lista de oraciones en español
spanish_sentences = [
    "El gato está en la casa.",
    "Estoy estudiando.",
    "El sol brilla en el cielo."
]

# Función para traducir oraciones usando M2M-100
def translate_m2m(sentences, source_lang="es", target_lang="en"):
    translations = []
    tokenizer.src_lang = source_lang  # Configurar idioma de origen (español)

    for sentence in sentences:
        # Tokenizar la oración y generar la traducción
        encoded = tokenizer(sentence, return_tensors="pt")
        generated_tokens = model.generate(**encoded, forced_bos_token_id=tokenizer.get_lang_id(target_lang))  # Configurar idioma objetivo (inglés)

        # Decodificar las traducciones a texto
        translated_text = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
        translations.append(translated_text[0])

    return translations

# Traducir oraciones del español al inglés usando M2M-100
translated_sentences_to_en = translate_m2m(spanish_sentences, source_lang="es", target_lang="en")

# Aquí deberías agregar el paso para traducir del inglés al quechua si tienes un modelo que lo haga
# Suponiendo que tienes un modelo que traduce del inglés al quechua, llamarlo aquí.
#translated_sentences_to_qu = translate_m2m(translated_sentences_to_en, source_lang="en", target_lang="qu")

# Mostrar las traducciones al inglés
print("Traducciones al inglés:")
print(translated_sentences_to_en)


Traducciones al inglés:
['The cat is in the house.', 'I am studying.', 'The sun shines in the sky.']


In [ ]:
from transformers import T5Tokenizer, T5ForConditionalGeneration
import torch
from sklearn.metrics.pairwise import cosine_similarity

# Cargar el modelo mT5 pequeño y el tokenizador
model_name = "google/mt5-small"  # Puedes probar con versiones más grandes como "mt5-base"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

# Lista de oraciones en español y quechua
spanish_sentences = [
    "El gato está en la casa.",
    "Estoy estudiando.",
    "El sol brilla en el cielo."
]

quechua_sentences = [
    "Misi wasipi kachkan.",  # El gato está en la casa.
    "Yachaykuyta ruwanqani.",  # Estoy estudiando.
    "Inti hanaqpachapi k'anchan."  # El sol brilla en el cielo.
]

# Función para generar embeddings usando mT5
def generate_embeddings(sentences):
    embeddings = []
    for sentence in sentences:
        # Tokenizar la oración y generar las representaciones (embeddings)
        input_ids = tokenizer(sentence, return_tensors="pt").input_ids
        with torch.no_grad():
            # Utiliza la capa de embeddings del modelo
            outputs = model.get_input_embeddings()(input_ids).mean(dim=1)  # Promedia sobre la longitud de la secuencia
            embeddings.append(outputs)

    return torch.cat(embeddings, dim=0)

# Generar embeddings para las oraciones en español y quechua
spanish_embeddings = generate_embeddings(spanish_sentences)
quechua_embeddings = generate_embeddings(quechua_sentences)

# Calcular la similitud del coseno entre cada oración en español y quechua
cosine_scores = cosine_similarity(spanish_embeddings.numpy(), quechua_embeddings.numpy())

# Mostrar la matriz de similitud
print("Matriz de Cosine Similarity:")
print(cosine_scores)


tokenizer_config.json:   0%|          | 0.00/82.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/553 [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
You are using a model of type mt5 to instantiate a model of type t5. This is not supported for all configurations of models and can yield errors.


pytorch_model.bin:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Matriz de Cosine Similarity:
[[0.40078494 0.36807674 0.39124006]
 [0.3446393  0.35369542 0.33683804]
 [0.32139605 0.34142154 0.34483224]]


In [ ]:
from transformers import T5Tokenizer, T5ForConditionalGeneration
import torch
from sklearn.metrics.pairwise import cosine_similarity

# Cargar el modelo mT5 grande y el tokenizador
model_name = "google/mt5-base"  # Cambiar a "mt5-large"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

# Lista de oraciones en español y quechua
spanish_sentences = [
    "El gato está en la casa.",
    "Estoy estudiando.",
    "El sol brilla en el cielo."
]

quechua_sentences = [
    "Misi wasipi kachkan.",  # El gato está en la casa.
    "Yachaykuyta ruwanqani.",  # Estoy estudiando.
    "Inti hanaqpachapi k'anchan."  # El sol brilla en el cielo.
]

# Función para generar embeddings usando mT5
def generate_embeddings(sentences):
    embeddings = []
    for sentence in sentences:
        # Tokenizar la oración y generar las representaciones (embeddings)
        input_ids = tokenizer(sentence, return_tensors="pt").input_ids
        with torch.no_grad():
            # Utiliza la capa de embeddings del modelo
            outputs = model.get_input_embeddings()(input_ids).mean(dim=1)  # Promedia sobre la longitud de la secuencia
            embeddings.append(outputs)

    return torch.cat(embeddings, dim=0)

# Generar embeddings para las oraciones en español y quechua
spanish_embeddings = generate_embeddings(spanish_sentences)
quechua_embeddings = generate_embeddings(quechua_sentences)

# Calcular la similitud del coseno entre cada oración en español y quechua
cosine_scores = cosine_similarity(spanish_embeddings.numpy(), quechua_embeddings.numpy())

# Mostrar la matriz de similitud
print("Matriz de Cosine Similarity:")
print(cosine_scores)


tokenizer_config.json:   0%|          | 0.00/376 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/702 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
You are using a model of type mt5 to instantiate a model of type t5. This is not supported for all configurations of models and can yield errors.


pytorch_model.bin:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Matriz de Cosine Similarity:
[[0.35711056 0.2900434  0.31860566]
 [0.29240096 0.23886615 0.3222313 ]
 [0.27987596 0.25389814 0.28992152]]


In [ ]:
from transformers import T5Tokenizer, T5ForConditionalGeneration
import torch
from sklearn.metrics.pairwise import cosine_similarity

# Cargar el modelo mT5 grande y el tokenizador
model_name = "google/mt5-large"  # Cambiar a "mt5-large"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

# Lista de oraciones en español y quechua
spanish_sentences = [
    "El gato está en la casa.",
    "Estoy estudiando.",
    "El sol brilla en el cielo."
]

quechua_sentences = [
    "Misi wasipi kachkan.",  # El gato está en la casa.
    "Yachaykuyta ruwanqani.",  # Estoy estudiando.
    "Inti hanaqpachapi k'anchan."  # El sol brilla en el cielo.
]

# Función para generar embeddings usando mT5
def generate_embeddings(sentences):
    embeddings = []
    for sentence in sentences:
        # Tokenizar la oración y generar las representaciones (embeddings)
        input_ids = tokenizer(sentence, return_tensors="pt").input_ids
        with torch.no_grad():
            # Utiliza la capa de embeddings del modelo
            outputs = model.get_input_embeddings()(input_ids).mean(dim=1)  # Promedia sobre la longitud de la secuencia
            embeddings.append(outputs)

    return torch.cat(embeddings, dim=0)

# Generar embeddings para las oraciones en español y quechua
spanish_embeddings = generate_embeddings(spanish_sentences)
quechua_embeddings = generate_embeddings(quechua_sentences)

# Calcular la similitud del coseno entre cada oración en español y quechua
cosine_scores = cosine_similarity(spanish_embeddings.numpy(), quechua_embeddings.numpy())

# Mostrar la matriz de similitud
print("Matriz de Cosine Similarity:")
print(cosine_scores)


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/376 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/642 [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
You are using a model of type mt5 to instantiate a model of type t5. This is not supported for all configurations of models and can yield errors.


pytorch_model.bin:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Matriz de Cosine Similarity:
[[0.27029765 0.2680447  0.25043666]
 [0.20891258 0.15934981 0.2477123 ]
 [0.25424564 0.2084991  0.24077046]]


estamos agregando algo para que se note la diferencia